const express=require('express');
const isAuth=require('../middleware/auth');
const { requireSelf }=require('../middleware/auth');
const { requireBodySelf }=require('../middleware/auth');
const { getAllProducts, getSingleProduct, getCartItems, addProductCart, deleteCartItem, updateCartItem, deleteCart, getStoreItems, getCafeItems } = require('../controllers/categoryController');
const { addCustomerOrder, getUserOrders } = require('../controllers/checkoutController');
const router=express.Router();
router.get("/getProducts", getAllProducts);
router.get("/getStore", getStoreItems);
router.get("/getCafe", getCafeItems);
router.get("/getSingleProduct/:id",getSingleProduct);
router.get("/getCartItems/:userId",isAuth,requireSelf("userId"),getCartItems);
router.delete("/deleteCart/:user_id",isAuth,requireSelf("user_id"),deleteCart);
router.post("/addProductCart",isAuth,requireBodySelf((body) => body.user_id),addProductCart);
router.delete("/deleteCartItem/:user_id/:cart_item_id",isAuth,requireSelf("user_id"),deleteCartItem);
router.put("/updateCartItem/:user_id/:cart_item_id",isAuth,requireSelf("user_id"),updateCartItem);
router.post("/placeOrder",isAuth,requireBodySelf((body) => body.formData?.user_id),addCustomerOrder);
router.get("/getOrders/:user_id",isAuth,requireSelf("user_id"),getUserOrders);

module.exports=router;
